# Generated by Django 4.2.6 on 2023-10-22 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='accounts.level')),
            ],
            options={
                'verbose_name': 'Бриф',
                'verbose_name_plural': 'Брифы',
            },
        ),
        migrations.CreateModel(
            name='MeetingsTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Тайм-слот встреч',
                'verbose_name_plural': 'Тайм-слоты встреч',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_start_time', models.TimeField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='TrainingStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='projects.brief')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
        migrations.CreateModel(
            name='ProjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_in_project', to='projects.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участие студента в проекте',
                'verbose_name_plural': 'Участие студента в проектах',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='projects.trainingstream'),
        ),
        migrations.CreateModel(
            name='MeetingsTimeSlotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetings_time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_time_slot', to='projects.meetingstimeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_time_slot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тайм-слот встреч пользователя',
                'verbose_name_plural': 'Тайм-слоты встреч пользователя',
            },
        ),
        migrations.AddField(
            model_name='meetingstimeslot',
            name='training_stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='projects.trainingstream'),
        ),
    ]
