# Generated by Django 4.2.6 on 2023-10-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_userpreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=10, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание проекта")),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brief",
                        to="accounts.level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бриф",
                "verbose_name_plural": "Брифы",
            },
        ),
    ]
