# Generated by Django 4.2.6 on 2023-10-22 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingstimeslotuser',
            old_name='user',
            new_name='student',
        ),
        migrations.AddField(
            model_name='meetingstimeslot',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
