# Generated by Django 4.2.6 on 2023-10-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_timeslot_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmanager",
            options={
                "verbose_name": "Проджект менеджер",
                "verbose_name_plural": "Проджект менеджеры",
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Команда", "verbose_name_plural": "Команды"},
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={"verbose_name": "Тайм-слот", "verbose_name_plural": "Тайм-слоты"},
        ),
    ]
