# Generated by Django 4.2.6 on 2023-10-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_projectmanager_options_alter_team_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="time_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="projects.timeslot",
            ),
        ),
    ]
