# Generated by Django 4.2.6 on 2023-10-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_projectstudent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectstudent",
            options={
                "verbose_name": "Участие студента в проекте",
                "verbose_name_plural": "Участие студента в проектах",
            },
        ),
        migrations.CreateModel(
            name="MeetingsTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "training_stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slot",
                        to="projects.trainingstream",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тайм-слот встреч",
                "verbose_name_plural": "Тайм-слоты встреч",
            },
        ),
    ]
