# Generated by Django 4.2.6 on 2023-10-21 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0005_alter_projectstudent_options_meetingstimeslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingsTimeSlotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meetings_time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings_time_slot",
                        to="projects.meetingstimeslot",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings_time_slot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Тайм-слот встреч пользователя",
                "verbose_name_plural": "Тайм-слоты встреч пользователя",
            },
        ),
    ]
