# Generated by Django 4.2.6 on 2023-10-19 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0006_alter_team_members_alter_team_project_manager_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "verbose_name": "Участие в команде",
                "verbose_name_plural": "Участие в команде",
            },
        ),
        migrations.RemoveField(
            model_name="membership",
            name="user",
        ),
        migrations.AddField(
            model_name="membership",
            name="member",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участник",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="membership",
            name="not_prefers_project_manager",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="non_preferred_project_manager",
                to="projects.projectmanager",
                verbose_name="Непредпочтительный ПМ",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="not_prefers_teammates",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="non_preferred_teammates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Непредпочтительный тиммейт",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="prefers_project_manager",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferred_project_manager",
                to="projects.projectmanager",
                verbose_name="Предпочитаемый ПМ",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="prefers_teammates",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="preferred_teammates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Предпочитаемый тиммейт",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.team",
                verbose_name="Команда",
            ),
        ),
    ]
