# Generated by Django 4.2.6 on 2023-10-22 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devmanuser',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.level'),
        ),
        migrations.DeleteModel(
            name='StudentLevel',
        ),
    ]
