# Generated by Django 4.2.6 on 2023-10-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="from_far_east",
            field=models.BooleanField(default=False, verbose_name="С Дальнего Востока"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(max_length=200, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="skill",
            field=models.CharField(
                choices=[
                    ("Новичок", "Новичок"),
                    ("Новичок+", "Новичок+"),
                    ("Джун", "Джун"),
                ],
                default="Новичок",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="surname",
            field=models.CharField(max_length=200, null=True, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="Электронный адрес"
            ),
        ),
    ]
