# Generated by Django 4.2.6 on 2023-10-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_levels_studentlevel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="levels",
            options={
                "verbose_name": "Уровень знаний",
                "verbose_name_plural": "Уровни знаний",
            },
        ),
    ]
