# Generated by Django 4.2.6 on 2023-10-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_options_alter_levels_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Levels",
            new_name="Level",
        ),
    ]
