# Generated by Django 4.2.6 on 2023-10-21 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_levels_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentlevel",
            options={
                "verbose_name": "Уровень студента",
                "verbose_name_plural": "Уровни студентов",
            },
        ),
        migrations.CreateModel(
            name="UserAvoidance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avoided_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avoiding_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Нежелательный тиммейт",
                "verbose_name_plural": "Нежелательные тиммейты",
            },
        ),
    ]
