# Generated by Django 4.2.6 on 2023-10-21 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="useravoidance",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avoiding_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userpreference",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferring_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="level",
            name="title",
            field=models.CharField(max_length=128, verbose_name="Уровень студента"),
        ),
        migrations.AlterField(
            model_name="useravoidance",
            name="avoided_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avoided_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="preferred_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferred_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
